[build-system]
requires = ["setuptools", "wheel", "pybind11>=2.6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "mahos"
version = "0.2.3"
description = "Measurement Automation Handling and Orchestration System"
readme = "README.rst"
requires-python = ">=3.8, <3.13"
license = { text = "BSD License (BSD-3-Clause)" }
keywords = [ "measurement automation", "laboratory automation", "instrumentation", ]
authors = [
    { name = "Kosuke Tahara", email = "ktaha@mosk.tytlabs.co.jp" },
]
classifiers = [
    "Programming Language :: Python :: 3",
]
dynamic = ["dependencies", "optional-dependencies"]

[project.urls]
Homepage = "https://github.com/ToyotaCRDL/mahos"
Documentation = "https://toyotacrdl.github.io/mahos"
Repository = "https://github.com/ToyotaCRDL/mahos.git"
Changelog = "https://github.com/ToyotaCRDL/mahos/blob/main/CHANGELOG.rst"

[project.scripts]
mahos = "mahos.cli.main:main"

[tool.setuptools]
zip-safe = false

[tool.setuptools.packages.find]
include = ["mahos*"]

[tool.setuptools.dynamic.dependencies]
file = ["requirements.txt"]

[tool.setuptools.dynamic.optional-dependencies.inst]
file = ["inst-requirements.txt"]

[tool.black]
line-length = 99
# mahos/gui/ui/*.py is auto-generated. test/podmr_patterns.py is too large.
extend-exclude = "(mahos/gui/ui|tests/podmr_patterns.py)"
