# Form implementation generated from reading ui file 'basic_meas.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_BasicMeas(object):
    def setupUi(self, BasicMeas):
        BasicMeas.setObjectName("BasicMeas")
        BasicMeas.resize(957, 707)
        self.verticalLayout = QtWidgets.QVBoxLayout(BasicMeas)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(parent=BasicMeas)
        self.tabWidget.setObjectName("tabWidget")
        self.measTab = QtWidgets.QWidget()
        self.measTab.setObjectName("measTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.measTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.startButton = QtWidgets.QPushButton(parent=self.measTab)
        self.startButton.setObjectName("startButton")
        self.horizontalLayout.addWidget(self.startButton)
        self.stopButton = QtWidgets.QPushButton(parent=self.measTab)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout.addWidget(self.stopButton)
        self.saveButton = QtWidgets.QPushButton(parent=self.measTab)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        self.exportButton = QtWidgets.QPushButton(parent=self.measTab)
        self.exportButton.setObjectName("exportButton")
        self.horizontalLayout.addWidget(self.exportButton)
        self.loadButton = QtWidgets.QPushButton(parent=self.measTab)
        self.loadButton.setObjectName("loadButton")
        self.horizontalLayout.addWidget(self.loadButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.methodBox = QtWidgets.QComboBox(parent=self.measTab)
        self.methodBox.setObjectName("methodBox")
        self.horizontalLayout_2.addWidget(self.methodBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.paramTable = ParamTable(parent=self.measTab)
        self.paramTable.setObjectName("paramTable")
        self.paramTable.setColumnCount(0)
        self.paramTable.setRowCount(0)
        self.verticalLayout_2.addWidget(self.paramTable)
        self.tabWidget.addTab(self.measTab, "")
        self.fiTab = QtWidgets.QWidget()
        self.fiTab.setObjectName("fiTab")
        self.tabWidget.addTab(self.fiTab, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(BasicMeas)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(BasicMeas)

    def retranslateUi(self, BasicMeas):
        _translate = QtCore.QCoreApplication.translate
        BasicMeas.setWindowTitle(_translate("BasicMeas", "Form"))
        self.startButton.setText(_translate("BasicMeas", "Start"))
        self.stopButton.setText(_translate("BasicMeas", "Stop"))
        self.saveButton.setText(_translate("BasicMeas", "Save"))
        self.exportButton.setText(_translate("BasicMeas", "Export"))
        self.loadButton.setText(_translate("BasicMeas", "Load"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.measTab), _translate("BasicMeas", "Main"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.fiTab), _translate("BasicMeas", "Fit"))
from mahos.gui.param import ParamTable
