# Form implementation generated from reading ui file 'compressionWidget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CompressionWidget(object):
    def setupUi(self, CompressionWidget):
        CompressionWidget.setObjectName("CompressionWidget")
        CompressionWidget.resize(367, 42)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CompressionWidget.sizePolicy().hasHeightForWidth())
        CompressionWidget.setSizePolicy(sizePolicy)
        CompressionWidget.setMaximumSize(QtCore.QSize(500, 16777215))
        self.horizontalLayout = QtWidgets.QHBoxLayout(CompressionWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=CompressionWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.methodBox = QtWidgets.QComboBox(parent=CompressionWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.methodBox.sizePolicy().hasHeightForWidth())
        self.methodBox.setSizePolicy(sizePolicy)
        self.methodBox.setMinimumSize(QtCore.QSize(0, 0))
        self.methodBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.methodBox.setObjectName("methodBox")
        self.methodBox.addItem("")
        self.methodBox.addItem("")
        self.methodBox.addItem("")
        self.horizontalLayout.addWidget(self.methodBox)
        self.levelBox = QtWidgets.QSpinBox(parent=CompressionWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.levelBox.sizePolicy().hasHeightForWidth())
        self.levelBox.setSizePolicy(sizePolicy)
        self.levelBox.setMinimumSize(QtCore.QSize(0, 0))
        self.levelBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.levelBox.setSuffix("")
        self.levelBox.setMinimum(1)
        self.levelBox.setMaximum(9)
        self.levelBox.setProperty("value", 4)
        self.levelBox.setObjectName("levelBox")
        self.horizontalLayout.addWidget(self.levelBox)

        self.retranslateUi(CompressionWidget)
        QtCore.QMetaObject.connectSlotsByName(CompressionWidget)

    def retranslateUi(self, CompressionWidget):
        _translate = QtCore.QCoreApplication.translate
        CompressionWidget.setWindowTitle(_translate("CompressionWidget", "Form"))
        self.label.setText(_translate("CompressionWidget", "Compression"))
        self.methodBox.setItemText(0, _translate("CompressionWidget", "lzf"))
        self.methodBox.setItemText(1, _translate("CompressionWidget", "gzip"))
        self.methodBox.setItemText(2, _translate("CompressionWidget", "None"))
        self.levelBox.setPrefix(_translate("CompressionWidget", "level: "))
