# Form implementation generated from reading ui file 'recorder.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Recorder(object):
    def setupUi(self, Recorder):
        Recorder.setObjectName("Recorder")
        Recorder.resize(957, 707)
        self.verticalLayout = QtWidgets.QVBoxLayout(Recorder)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.startButton = QtWidgets.QPushButton(parent=Recorder)
        self.startButton.setObjectName("startButton")
        self.horizontalLayout.addWidget(self.startButton)
        self.stopButton = QtWidgets.QPushButton(parent=Recorder)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout.addWidget(self.stopButton)
        self.resetButton = QtWidgets.QPushButton(parent=Recorder)
        self.resetButton.setObjectName("resetButton")
        self.horizontalLayout.addWidget(self.resetButton)
        self.saveButton = QtWidgets.QPushButton(parent=Recorder)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        self.exportButton = QtWidgets.QPushButton(parent=Recorder)
        self.exportButton.setObjectName("exportButton")
        self.horizontalLayout.addWidget(self.exportButton)
        self.loadButton = QtWidgets.QPushButton(parent=Recorder)
        self.loadButton.setObjectName("loadButton")
        self.horizontalLayout.addWidget(self.loadButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelBox = QtWidgets.QComboBox(parent=Recorder)
        self.labelBox.setObjectName("labelBox")
        self.horizontalLayout_2.addWidget(self.labelBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.paramTable = ParamTable(parent=Recorder)
        self.paramTable.setObjectName("paramTable")
        self.paramTable.setColumnCount(0)
        self.paramTable.setRowCount(0)
        self.verticalLayout.addWidget(self.paramTable)

        self.retranslateUi(Recorder)
        QtCore.QMetaObject.connectSlotsByName(Recorder)
        Recorder.setTabOrder(self.startButton, self.stopButton)
        Recorder.setTabOrder(self.stopButton, self.resetButton)
        Recorder.setTabOrder(self.resetButton, self.saveButton)
        Recorder.setTabOrder(self.saveButton, self.exportButton)
        Recorder.setTabOrder(self.exportButton, self.loadButton)
        Recorder.setTabOrder(self.loadButton, self.labelBox)
        Recorder.setTabOrder(self.labelBox, self.paramTable)

    def retranslateUi(self, Recorder):
        _translate = QtCore.QCoreApplication.translate
        Recorder.setWindowTitle(_translate("Recorder", "Form"))
        self.startButton.setText(_translate("Recorder", "Start"))
        self.stopButton.setText(_translate("Recorder", "Stop"))
        self.resetButton.setText(_translate("Recorder", "Reset"))
        self.saveButton.setText(_translate("Recorder", "Save"))
        self.exportButton.setText(_translate("Recorder", "Export"))
        self.loadButton.setText(_translate("Recorder", "Load"))
from mahos.gui.param import ParamTable
